#!/usr/bin/env python3
"""Tor v3 onion address codec -- stdlib only.

Per rend-spec-v3, a v3 onion address is:

    address = base32( pubkey (32B) || checksum (2B) || version (1B) )

    checksum = SHA3-256( ".onion checksum" || pubkey || version )[:2]
    version  = 0x03

The 35 bytes base32-encode to 56 lowercase characters (no padding).
The checksum means an address is *self-validating*: anyone can check that
an address is well-formed, but only the ed25519 private-key holder can
prove ownership of it.
"""
import base64
import hashlib

CHECKSUM_PREFIX = b".onion checksum"
VERSION = 0x03
PUBKEY_LEN = 32


def encode_onion(pubkey: bytes) -> str:
    """Build the v3 onion address (without '.onion') for a 32-byte pubkey."""
    if len(pubkey) != PUBKEY_LEN:
        raise ValueError(f"ed25519 pubkey must be {PUBKEY_LEN} bytes")
    checksum = hashlib.sha3_256(CHECKSUM_PREFIX + pubkey + bytes([VERSION])).digest()[:2]
    raw = pubkey + checksum + bytes([VERSION])
    return base64.b32encode(raw).decode("ascii").lower()


def decode_onion(addr: str):
    """Split an onion address -> (pubkey, checksum, version). Raises ValueError."""
    a = addr.lower().strip()
    if a.endswith(".onion"):
        a = a[:-len(".onion")]
    if len(a) != 56:
        raise ValueError(f"v3 onion address must be 56 chars, got {len(a)}")
    try:
        raw = base64.b32decode(a.upper())
    except Exception as e:
        raise ValueError(f"not valid base32: {e}") from e
    if len(raw) != 35:
        raise ValueError(f"decoded to {len(raw)} bytes, want 35")
    return raw[:32], raw[32:34], raw[34]


def validate_onion(addr: str):
    """Validate a v3 onion address. Returns (ok, detail)."""
    try:
        pubkey, checksum, version = decode_onion(addr)
    except ValueError as e:
        return False, str(e)
    if version != VERSION:
        return False, f"unknown version {version} (want {VERSION})"
    want = hashlib.sha3_256(CHECKSUM_PREFIX + pubkey + bytes([version])).digest()[:2]
    if checksum != want:
        return False, (f"CHECKSUM MISMATCH: embedded {checksum.hex()}, "
                       f"recomputed {want.hex()} -- address is forged/typo'd")
    return True, (f"valid v3 address; ed25519 pubkey={pubkey.hex()}; "
                  f"checksum {checksum.hex()} ok")


# Test vectors: generated by encode_onion itself from fixed public keys, then
# hardcoded so the self-test pins the codec (not just round-trips it).
_TEST_VECTORS = [
    # pubkey = bytes(range(32))
    "aaaqeayeaudaocajbifqydiob4ibceqtcqkrmfyydenbwha5dyp3kead",
    # pubkey = sha256(b"scout test vector one")
    "i6fvc44emf473zdelgomnmq6zceyaulwaoijvc6sgpgdrzorj33kvkyd",
]


def _regenerate_vectors():
    keys = [bytes(range(32)),
            hashlib.sha256(b"scout test vector one").digest()]
    return [encode_onion(k) for k in keys]


def self_test():
    ok = True
    # 1. hardcoded vectors must validate (pins the implementation)
    for i, (vec, key) in enumerate(zip(_TEST_VECTORS, _regenerate_vectors())):
        match = (vec == key)
        valid, detail = validate_onion(vec)
        good = match and valid
        ok = ok and good
        print(f"[{'PASS' if good else 'FAIL'}] vector {i}: pinned={match} "
              f"valid={valid} ({detail[:60]}...)")
    # 2. round-trip on random keys
    import os
    for _ in range(5):
        k = os.urandom(32)
        valid, _ = validate_onion(encode_onion(k))
        ok = ok and valid
    print(f"[{'PASS' if ok else 'FAIL'}] 5 random round-trips")
    # 3. corruption detected (flip last char)
    bad = _TEST_VECTORS[0][:-1] + ("a" if _TEST_VECTORS[0][-1] != "a" else "b")
    valid, detail = validate_onion(bad)
    good = not valid
    ok = ok and good
    print(f"[{'PASS' if good else 'FAIL'}] corrupted address rejected: {detail[:70]}")
    # 4. wrong length / garbage rejected
    for junk in ["short.onion", "facebookcorewwwi.onion", "!!!"]:
        valid, _ = validate_onion(junk)
        ok = ok and not valid
    print(f"[{'PASS' if ok else 'FAIL'}] junk inputs rejected")
    # 5. real-world address (DuckDuckGo's v3 onion, from memory -- honest check)
    ddg = "duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion"
    valid, detail = validate_onion(ddg)
    print(f"[{'PASS' if valid else 'FAIL'}] DuckDuckGo v3 onion: {detail[:80]}")
    print("ONION SELF-TEST:", "PASS" if ok else "FAIL")
    return ok


if __name__ == "__main__":
    raise SystemExit(0 if self_test() else 1)
